master:
  node_id: 1
  driver: "ros2_canopen::MasterNode"
  package: "canopen_core"

proxy_device_1:
  node_id: 2
  dcf: "simple/simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false

proxy_device_2:
  node_id: 3
  dcf: "simple/simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false